version: '3.5'
services:
  web-service1:
    container_name: myapp1
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db-service
  web-service2:
    container_name: myapp2
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db-service
  proxy-service:
    container_name: myproxy
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy:/app
    ports:
      - "8000:8000"
  db-service:
    container_name: mydb
    image: postgres:alpine
    volumes:
      - psql-data:/var/lib/postgresql/data
volumes:
  psql-data:
    driver: local
