version: '3.5'
services:
  web-service:
    build: .
    volumes:
      - ./lib:/app/lib
      - ./public:/app/public
      - ./app.js:/app/app.js
      - ./server.js:/app/server.js
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db-service
  proxy-service:
    container_name: myproxy
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/src:/app/src
      - ./reverse-proxy/app.js:/app/app.js
      - ./reverse-proxy/config.json:/app/config.json
      - ./reverse-proxy/server.js:/app/server.js
    ports:
      - "8000:8000"
  db-service:
    container_name: mydb
    image: postgres:alpine
    volumes:
      - psql-data:/var/lib/postgresql/data
volumes:
  psql-data:
    driver: local
